gpuBurn:
  matrixMulResult: FAIL
  commandToRun: echo Allspark | sudo -S /home/allspark/service_apps/gpuBurn.sh
asapp:
  maxTemp: 60
  commandToRun: echo Allspark | sudo -S /home/allspark/service_apps/asapp -O -M -T
wifiFlooding:
  timeoutinMs: 100
  commandToRun: ping -i 0.2 -s 65507 192.168.1.1
latency:
  maxFrameLatency: 3
  commandToRun: echo Allspark | sudo -S /home/allspark/service_apps/loopback.sh
